### ISSUE TITLE
fatal error: tjpgd.h: No such file or directory

### ISSUE THREAD

**Issue by superquala** [nopnop2002/esp-idf-video-streaming#13]
Hi
when I want to build the code, I receive this error and "compilation terminated"!
first of all let me tell you that I hadn't worked with esp-idf before. I've used Arduino to work with esp chips and this is the first time I use esp-idf. 
 these are my steps:
I installed esp-idf v5.0 with all tools and etc
then I opened "ESP-IDF 5.0 CMD" and copy and paste your installation phrase. I mean these:
git clone https://github.com/nopnop2002/esp-idf-video-streaming
cd esp-idf-video-streaming
idf.py set-target {esp32s2}
idf.py menuconfig
idf.py flash monitor

I don't know is it the correct way to build a project in esp-idf! for Arduino I always download the code but I think no need to download the code for esp-idf, just copy and paste the code path is OK, right? 

after all these steps when the code are compiling and building, this error happen:
fatal error: tjpgd.h: No such file or directory

so could you pls help me and tell me the reason?
thanks

**Comment by nopnop2002** [comment]
Thank you for your report.

Fixed a compilation error in the latest version.

Note:

This example requires any ESP32-S2 or ESP32-S3 __with external PSRAM.__

ESP module without external PSRAM will fail to initialize.

**Comment by superquala** [comment]
thank you so much for solving the problem. 
I use esp32-s2 pico with 8MB PSRAM
I upload the code on my esp-s2 board, it connect to my phone through hotspot successfully but unfortunately it can't connect to my camera. my error is different from the error you mentioned. 
this is my terminal :
![uvc problem](https://user-images.githubusercontent.com/123031714/213341275-77855988-0f9e-4e81-9cec-4026dfa1d979.JPG)

when I connect the camera to the esp usb port, the board restarts 
I try with two camera and different settings.
I can't open the http address too!
do you know what is the problem?

**Comment by nopnop2002** [comment]
i want to see all log output

Attach log output (log.txt) here.

**Comment by nopnop2002** [comment]
I know what caused the panic.
It's an ESP32S2 specific problem.
I found a workaround so I avoided it
Fixed in the latest version.

**Comment by superquala** [comment]
Thanks bro but I couldn't get image yet
I think I should switch to esp32-s3 : ) !
with this new updated code I realized that one of my cameras not supported but the other one has same problem like before. I attach the text files of both cameras. pls check
 
[cam1.txt](https://github.com/nopnop2002/esp-idf-video-streaming/files/10463017/cam1.txt)
[cam2.txt](https://github.com/nopnop2002/esp-idf-video-streaming/files/10463018/cam2.txt)

**Comment by nopnop2002** [comment]
cam1.txt doesn't recognize the camera at all.


```
I (5568) HTTP: Starting HTTP server on http://192.168.191.178:8080
Waiting for device
```




cam2.txt recognizes the camera, but the format specified in the menu does not match.
```
W (11323) example: FRAME SIZE=320x240 FRAME RATE=15
W (11333) example: FRAME FORMAT=MJPEG
```

Change the FRAME FORMAT from MJPEG to UncompressedFormat using menuconfug.

__It is very hard to find a camera that works with ESP-IDF.__
If you are lucky, it might work.

Older MicroSoft cameras work pretty well.

Microsoft LifeCam Cinema -> Success
Microsoft LifeCam Studio -> Success
Microsoft LifeCam HD3000 -> Success
Microsoft LifeCam HD5000 -> Success

---

>I think I should switch to esp32-s3 : ) !

The latest also works with esp32-s2.


This is working on an ESP32-S2.
I am streaming TV.


![esp32s2-capture](https://user-images.githubusercontent.com/6020549/213627334-4bef80db-a90f-4bc8-9e39-59750fca36df.jpg)

**Comment by superquala** [comment]
I try with another format and also different qualities but nothing change,
Same results

I couldn't find any Microsoft webcam in my place but I find Logitech c270 in an online shop, it's OK right?

**Comment by superquala** [comment]
I want to try this code with uvc cam to compare it with esp-cam module(with ov2640 camera)
Have you worked with esp-cam before ?
If yes, could you please tell me which one is better totaly?
For example in same quality like 240×320 or 640×480 
Which one has more fps?
Which one has lower latency?

**Comment by nopnop2002** [comment]
>For example in same quality like 240×320 or 640×480

esp-cam module(with ov2640 camera) 320x240
It takes about 40 ticks (0.4 seconds) to acquire one frame.
About 2.5fps.

```
I (16026) MAIN: fb->len=7829
I (16056) MAIN: fb->len=6271
I (16096) MAIN: fb->len=6271
I (16136) MAIN: fb->len=6114
I (16176) MAIN: fb->len=6522
I (16406) MAIN: fb->len=6566
```

esp-cam module(with ov2640 camera) 640x320
It takes about 80 ticks (0.8 seconds) to acquire one frame.
About 1.25 fps.

```
I (10526) MAIN: fb->len=23540
I (10576) MAIN: fb->len=19717
I (10656) MAIN: fb->len=19561
I (10736) MAIN: fb->len=19426
I (10816) MAIN: fb->len=19571
I (11256) MAIN: fb->len=19531
```
---

Logitech c270 is 160x120 10FPS performance.

```
DEVICE CONFIGURATION (046d:0825/2) ---
Status: idle
VideoControl:
        bcdUVC: 0x0100
VideoStreaming(1):
        bEndpointAddress: 129
        Formats:
        UncompressedFormat(1)
                  bits per pixel: 16
                  GUID: 5955593200001000800000aa00389b71 (YUY2)
                  default frame: 1
                  aspect ratio: 0x0
                  interlace flags: 00
                  copy protect: 00
                        FrameDescriptor(1)
                          capabilities: 01
                          size: 160x120
                          bit rate: 3072000-3072000
                          max frame size: 38400
                          default interval: 1/10
                          interval[0]: 1/10
END DEVICE CONFIGURATION
```

---

>I couldn't find any Microsoft webcam in my place


Do you have a auction site in your country?
Used Microsoft WebCams are available in my country for less than $10.
Microsoft's old webcam is much better than the Logitech c270.

**Comment by superquala** [comment]
thank you so much 
about esp-cam I'm sure it can handle much more fps. check this: https://www.youtube.com/watch?v=gE3DyYze8c8

I found a camera that is very similar to one of the cameras in your picture. this one:
![cam](https://user-images.githubusercontent.com/123031714/213863820-db69ddfa-b2f1-452f-82c2-d44262ca5362.JPG)

but I don't find its name in your list. Is it OK with esp-idf?

and last question, most of us want to connect usb cam to esp chips fpr our DIY projects not just as a online webcam. so we want to use small camera modules instead of old webcams but as you mentioned, esp-idf don't support most of them. 
do you think is it from coding? and can be solved?
or it's limit of esp chips and there isn't any solution?

**Comment by nopnop2002** [comment]
>about esp-cam I'm sure it can handle much more fps

The number of colors in the image you capture and the movement of the image can greatly affect performance.

And the magic of this video is capturing static color images and moving monochrome images.
Since MPEG only provides the difference between the previous image and the latest image, 
It can provide images with little motion very quickly.
A monochrome image is a much smaller image than a color image.
Black and white metronome capture works very fast.

Firmware is here.
https://github.com/espressif/esp-who/tree/release/v1.0/examples/single_chip/camera_web_server


The camera you marked is a Microdia product and released as an OEM.
Microdia(Very old model) -> Success
```
$ lsusb
Bus 001 Device 042: ID 0c45:6340 Microdia Camera
```
This camera is a product of Sonix Technology and sold as an OEM.
It was sold as the following model. I'm sure there are many more.
- SANWA SUPPLY CMS-V30SETBK
- SANWA SUPPLY CMS-V34BK
- Canyon CNE-CWC1
- Canyon CNR-FWC113
- GearHead WC7500HD
- GearHead WC8500HD
- Papalook PA150

>so we want to use small camera modules instead of old webcams

>do you think is it from coding? and can be solved?

No
To support more USB cameras, only EspressIF can do.
If you are familiar with ESP-IDF and have enough time, you can contribute your newly developed code to EspressIF.
EspressIF will merge your developed code into ESP-IDF



>or it's limit of esp chips and there isn't any solution?

It's not a limit of ESP chip.
ESP-IDF does not support these cameras.



I haven't tried it, but the Raspberry Pi Zero might be faster when it comes to image processing.
