### ISSUE TITLE
USB CAMERA 

### ISSUE THREAD

**Issue by Nadeemranm** [nopnop2002/esp-idf-video-streaming#15]
![WhatsApp Image 2023-05-02 at 16 33 30](https://user-images.githubusercontent.com/130030462/235649633-667d0e9b-d217-4dba-913c-7d29f8419da9.jpeg)
  I face this type of issue when i connect the usb camera
help me resolve this error

**Comment by nopnop2002** [comment]
It is very hard to find a camera that works with ESP-IDF.
I tested with these cameras.

Logitech C270 -> Success
Logitech C615 -> Fail
Logitech QuickCam Pro 9000 -> Fail
PAPALOOK AF925 -> Fail
Microdia(Very old model) -> Success
Microdia MSI Starcam Racer -> Success
Microsoft LifeCam NX6000 -> Fail
Microsoft LifeCam Cinema -> Success
Microsoft LifeCam Studio -> Success
Microsoft LifeCam HD3000 -> Success
Microsoft LifeCam HD5000 -> Success

**Comment by Nadeemranm** [comment]
[image: WhatsApp Image 2023-05-02 at 18.37.44.jpeg]
now i faced this problem
[image: WhatsApp Image 2023-05-02 at 18.39.54.jpeg]
This is my usb camera
Plz help me to resole this error

**Comment by nopnop2002** [comment]
There is no solution other than using a camera supported by ESP-IDF.


You can ask to add cameras that ESP-IDF supports here.


https://github.com/espressif/esp-idf/issues


Supporting more cameras is a problem for EspressIF to solve, not a problem for us.

**Comment by Nadeemranm** [comment]
Please help i just very close of this
What should I do here
Streaming but code not running ahead
And an error pop-up here libusb adaptor?

**Comment by nopnop2002** [comment]
>What should I do here

There is 2 way.

- Ask EspressIF to support your camera.
https://github.com/espressif/esp-idf/issues

- Buy ESP-IDF Supported Cameras


**ESP-IDF only supports a very limited cameras.**
**You are trying to use a camera that ESP-IDF does not support.**

This is an ESP-IDF issue.
It's not an issue for this project.

**Supporting more cameras is a problem for EspressIF to solve, not a problem for us.**

**Comment by Nadeemranm** [comment]
This can be possible any usb camera support the uvc driver but working with
"ESP-IDF" ?

**Comment by nopnop2002** [comment]
>This can be possible any usb camera support the uvc driver but working with "ESP-IDF" ?

Only few USB cameras with uvc driver support work with ESP-IDF.
Only few USB cameras is abailable.
Only few USB cameras work with ESP-IDF.

Logitech C980 works with ESP-IDF.


If you buy C980, this official sample will work.
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/uvc

**Comment by Nadeemranm** [comment]
good morning
can you give me some time for zoom call meeting today ?
