### ISSUE TITLE
usb camera with esp32s3 

### ISSUE THREAD

**Issue by Nadeemranm** [nopnop2002/esp-idf-video-streaming#16]
I have two usb cameras but not working any of them
different different error pop-up of  them's
![WhatsApp Image 2023-05-02 at 16 33 30](https://github.com/nopnop2002/esp-idf-video-streaming/assets/130030462/2baff675-e2a2-4b51-8b4a-e8be57ee0970)
![WhatsApp Image 2023-05-12 at 12 22 54](https://github.com/nopnop2002/esp-idf-video-streaming/assets/130030462/c1d0b63f-aff7-4f02-a752-7911d0647db1)
pls help

**Comment by nopnop2002** [comment]
Change camera,

Try with Logitech C270 or C980 or Microsoft cameras.

ESP-IDF only supports a few USB cameras.

Most USB cameras cannot be used.

**Comment by Nadeemranm** [comment]
How i faced this problem
In code where I should be change

**Comment by nopnop2002** [comment]
>In code where I should be change

https://github.com/espressif/esp-idf/tree/master/components/usb

Ask EspressIF.

--------------------------
I have explained it before.


This is an ESP-IDF driver issue.


You are using an unsupported camera.

You need to change your camera.

There is no other way.

**Comment by nopnop2002** [comment]
can you understand my english?

Have you read my README?

There is solution in my README.

**Comment by Nadeemranm** [comment]
Yes💯

**Comment by Nadeemranm** [comment]
good morning
Sir can you give me some time  for video call zoom meeting today?
i have same issue so that i want discusse with you

**Comment by nopnop2002** [comment]
>Sir can you give me some time  for video call zoom meeting today?

No.


Due to the time difference, real-time conversations are difficult.

Good night.

**Comment by Nadeemranm** [comment]
Sir respond will be  by email or zoom call meeting ?
I want be only 10 to 15 minutes  on zoom call
Whenever are you free . I am available any time

**Comment by nopnop2002** [comment]
good morning

Due to the time difference, real-time conversations are difficult.

and i can't speak english.

I will go to my office and  work till night.

**Comment by Nadeemranm** [comment]
sir please give me only 5 minutes for zoom call conversation . sir your
help will be very helpful for me


thank you

**Comment by nopnop2002** [comment]
I can't catch English.

If you can speak Japanese, I can have a meeting with you.

If you have a Japanese interpreter, I can have a meeting with you.

Good night.
