### ISSUE TITLE
Embedded PSRAM SOC

### ISSUE THREAD

**Issue by Akashjain2996** [nopnop2002/esp-idf-video-streaming#20]
Can we use ESP32 S2 SOC with 2MB embedded PSRAM.
Would the code work well with it?

**Comment by nopnop2002** [comment]
If it have USB port, it'll probably be fine.

**Comment by Akashjain2996** [comment]
Thanks for the reply.
We are planning to use ESP32-S2FN4R2. It has 4MB flash and 2MB PSRAM. It USB Full speed support.
Would this be good to go?

**Comment by nopnop2002** [comment]
It should be fine.
